services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/ontology"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE=http://backend:8000
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5174"
    volumes:
      - ./frontend:/web
      - frontend_node_modules:/web/node_modules
    depends_on:
      backend:
        condition: service_healthy

volumes:
  frontend_node_modules:
